<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Home</title>
    <link rel="stylesheet" href="./css/style.css" />
  </head>
  <body>
  <div class="grid-container">
    <div class="header">
      <div class="header_left">
        <div>Menu</div>
      </div>
      <div class="header_center">
        <h2>Quản Lý Kho Hàng</h2>
      </div>
      <div class="header_right">Liên Kết</div>
    </div>
    <div class="menu menu_active">
			<a href="https://tueduc.net/quanlykho/"><img width="120" src="../images/logo.png" /></a>
      <div class="block_ava">
        <a href="#"><img src="../images/ava_hue.jpg" /></a>
        <p>Xin chào,<span>Ms. Huệ!</span></p>
          </div>
         
    </div>
    <div class="isd_main">
      <div class="main_content">
            DYNAMIC
      </div>
	  </div>  
  </div>
		<script>
      window.ISD_BASE_URL = '<?php echo $data['base_url'] ?>/';
    </script>
		<script src="<?php echo $data['base_url'] ?>/js/jquery.min.js"></script>
		<script src="<?php echo $data['base_url'] ?>/js/lotusapp_custom.js"></script>
  </body>
</html>