<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Home</title>
    <link rel="stylesheet" href="./css/antd.min.css" />
    <link rel="stylesheet" href="./css/style.css" />
    
  </head>
  <body>
    <div id="isd_app"></div>
    <script>
      window.ISD_BASE_URL = '<?php echo $data['base_url'] ?>/';
    </script>
    <!-- <script src="<?php echo $data['base_url'] ?>/js/vendors.min.js"></script>
    <script src="<?php echo $data['base_url'] ?>/js/lotus.min.js"></script> -->
    <script src="http://localhost:8080/public/lotus.min.js"></script>
  </body>
</html>