<?php 
$serverName = $_SERVER['SERVER_NAME'];
$jsUrl = $data['base_url'];
switch($serverName) {
 case 'localhost':
 case 'erpapp':
 case 'annhien':
 case 'lotus':
 case '127.0.0.1':
   //If webpack server is running, then reference all files from there
   $devServerContent = @file_get_contents('http://localhost:8080/public/lotus.min.js');
   if($devServerContent !== false) {
     $jsUrl = 'http://localhost:8080/public';
   }
   break;
 default:
  $jsUrl = $data['base_url'];
   break;
}
/** End check asset path for developer purpose **/
?>

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Home</title>
    <link rel="stylesheet" href="./css/antd.min.css" />
    <link rel="stylesheet" href="./css/style.css" />
    <link rel="stylesheet" href="./css/responsive.css" />
    
  </head>
  <body>
    <div id="isd_app"></div>
    <script>
      window.ISD_BASE_URL = '<?php echo $data['base_url'] ?>/';
    </script>
    <?php if(strpos($jsUrl, '8080') !== false) : ?>
    <script src="<?php echo $jsUrl ?>/lotus.min.js"></script>
    <?php else : ?>
    <script src="<?php echo $jsUrl ?>/js/vendors.min.js"></script>
    <script src="<?php echo $jsUrl ?>/js/lotus.min.js"></script>
    <?php endif; ?>
  </body>
</html>