<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Home</title>
    <link rel="stylesheet" href="./css/login.css" />
  </head>
  <body>
  <div class="background-wrap">
    <div class="background"></div>
  </div>
  <form id="accesspanel">
      <h1 id="litheader">Lotus Company</h1>
      <div class="inset">
        <p>
          <input required autocomplete="off" type="text" name="username" id="email" placeholder="Email address">
        </p>
        <p>
          <input required type="password" name="password" id="password" placeholder="Mật khẩu">
        </p>
        <input class="loginLoginValue" type="hidden" name="service" value="login" />
      </div>
      <p class="p-container">
        <input type="button" name="Login" id="submit" value="Đăng Nhập">
      </p>
    </form>
    <script>
      window.ISD_BASE_URL = '<?php echo $data['base_url'] ?>/';
      let submitBtn = document.getElementById('submit'),
          email = document.querySelector("#email"),
          password = document.querySelector("#password");
      submitBtn.addEventListener('click', function() {
        if(email.value == "" || password.value == "") {
          alert("Email hoặc password trống!");
          return false;
        }
        let headerText = document.querySelector("#litheader");
        headerText.classList.add('poweron');
        fetch(ISD_BASE_URL + 'token', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({
            email: email.value,
            password: password.value
          })
        })
        .then((response) => response.json())
        .then((json) => {
          if(json.token) {
            localStorage.setItem('isd_token', json.token);
          }
        })
        .catch((error) => {
          console.log(error);
        });
      });
    </script>
  </body>
</html>